proxy:
  build: proxy
  ports:
    - "8080:8080"
  links:
    - mapfishapp
    - urbanisme
    - header
    - cadastrapp
  environment:
    - XMX=512M
  extra_hosts:
    - portail-test.sig.rennesmetropole.fr:10.26.10.8
mapfishapp:
  environment:
    - XMX=1024M
  image: georchestra/mapfishapp
  # directory relative to ${project.basedir}/target/docker
  volumes:
    - ../../src/addon/urbanisme:/etc/georchestra/mapfishapp/addons/urbanisme
cadastrapp:
  build: cadastrapp
  environment:
    - XMX=512M
urbanisme:
  build: urbanisme
  environment:
    - ADD_JAVA_OPTS=-Dgeorchestra.datadir=/etc/georchestra
header:
  environment:
    - XMX=512M
  image: georchestra/header
